apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T06:44:13Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3549"
  uid: 9ed33d2c-05ff-4b80-adc8-603af81684a1
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.228.128
  clusterIPs:
  - 10.104.228.128
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31232
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
